######################## default configuration ####################
baseURL = "https://demo.gethugothemes.com/godocs/style-2/"
title = "Hugo documentation theme"
theme = "godocs-2"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disable language
disableLanguages = [] # desable language from here

# hugo outputs
[outputs]
home = [ "HTML", "JSON"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/search/auto-complete.css"
[[params.plugins.css]]
link = "plugins/featherlight/featherlight.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"
[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"
[[params.plugins.js]]
link = "plugins/featherlight/featherlight.min.js"
[[params.plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
[[params.plugins.js]]
link = "plugins/search/auto-complete.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/search/lunr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search-page.js"

# site variables
[params.variables]
# Color Variables
primary_color = "#FF0043"
text_color = "#333"
text_color_dark = "#222"
text_color_light = "#999"
body_color = "#fff"
border_color = "#E2E2E2"
black = "#000"
white = "#fff"
light = "#FBFBFB"

# Font Variables
primary_font = "Montserrat:wght@300;400;500;600;700;800"
primary_font_type = "sans-serif" # [serif/sans-serif]
secondary_font = ""
secondary_font_type = "" # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"


#################### default parameters ################################
[params]
logo = "images/logo.png"
favicon = "images/favicon.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[[params.nav_button]]
style = "outline" # available style: solid, outline
label = "changelog"
link = "changelog"

[[params.nav_button]]
style = "solid" # available style: solid, outline
label = "Contact"
link = "contact"

  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon : https://fontawesome.com/icons
link = "#"

[[params.social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon : https://fontawesome.com/icons
link = "#"

[[params.social]]
title = "github"
icon = "fab fa-github" # fontawesome icon : https://fontawesome.com/icons
link = "#"

[[params.social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon : https://fontawesome.com/icons
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
# copyright
copyright = "Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

# call to action
[Languages.en.call_to_action]
enable = true
title = "Still Didn't Find Your Answer?"
image = "images/cta-illustration.jpg"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam <br> nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"

  # call to action button
  [Languages.en.call_to_action.button]
  enable = true
  label = "Submit a ticket"
  link = "contact"


############## English navigation ###############
# main menu
[[Languages.en.menu.main]]
name = "Home"
url = ""
weight = 1

[[Languages.en.menu.main]]
name = "FAQ"
url = "faq"
weight = 2


# footer menu
[[Languages.en.menu.footer]]
name = "Changelog"
url = "changelog"
weight = 1

[[Languages.en.menu.footer]]
name = "Contact"
url = "contact"
weight = 2

[[Languages.en.menu.footer]]
name = "Github"
url = "https://github.com/themefisher/"
weight = 3


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 2
# copyright
copyright = "Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

# call to action
[Languages.fr.call_to_action]
enable = true
title = "Still Didn't Find Your Answer?"
image = "images/cta-illustration.jpg"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam <br> nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"

  # call to action button
  [Languages.fr.call_to_action.button]
  enable = true
  label = "Submit a ticket"
  link = "contact"


############## French navigation ###############
# main menu
[[Languages.fr.menu.main]]
name = "Home"
url = ""
weight = 1

[[Languages.fr.menu.main]]
name = "FAQ"
url = "faq"
weight = 2


# footer menu
[[Languages.fr.menu.footer]]
name = "Changelog"
url = "changelog"
weight = 1

[[Languages.fr.menu.footer]]
name = "Contact"
url = "contact"
weight = 2

[[Languages.fr.menu.footer]]
name = "Github"
url = "https://github.com/themefisher/"
weight = 3